---
services:  
  keycloak:    
    image: quay.io/keycloak/keycloak:23.0.3
    command: start-dev --import-realm
    environment:      
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_svr
      KC_DB_URL_DATABASE: keycloakclaimadministrator
      KC_DB_PASSWORD: keycloakclaimadministrator
      KC_DB_USERNAME: keycloakclaimadministrator
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      postgres_svr:
        condition: service_healthy
    networks:
      network_sso:
    volumes:
      - /home/andriy/Documents/sources/my_docker_composes/keycloak_and_postgres/data/:/opt/keycloak/data

  postgres_svr: 
    image: postgres:15
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'
    environment:
      # Environment Variables expecially for Postgres
      POSTGRES_DB: keycloakclaimadministrator
      POSTGRES_USER: keycloakclaimadministrator
      POSTGRES_PASSWORD: keycloakclaimadministrator
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
    networks:
      network_sso:
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:  
  network_sso:
volumes:
  postgres_data: