services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  rabbitmq:
    container_name: rabbit_to_elastic
    image: rabbitmq:management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Named volume for RabbitMQ data
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management plugin port

volumes:
  esdata1:
  rabbitmq_data:
networks:
  esnet:
