services:

  # You would be asked to create password for container on first login
  # Use it if you want to visualize containers 
  # localhost:9003 // UI
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer_pa
    command: -H unix:///var/run/docker.sock
    ports:
      - "9003:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    restart: unless-stopped
volumes:
  portainer_data: {}

