version: "3"
services:
  rabbitmq:
    container_name: krolik
    image: rabbitmq:management
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management plugin port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Named volume for RabbitMQ data

  redis:
    container_name: rediska
    image: redis
    ports:
      - "6379:6379" # Redis default port

  minio:
    image: quay.io/minio/minio:latest
    container_name: 'minion'
    command: server --console-address ":9001" /data
    ports: 
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/mnt/data

volumes:
  rabbitmq_data:
  minio-data:



